x-vanilla: &vanilla
    build:
        context: .
        dockerfile: docker/vanilla.Dockerfile
        args:
            DATABASE_URL: ${DATABASE_URL}
    depends_on:
        migrations:
            condition: service_completed_successfully

x-api: &api
    build:
        context: .
        dockerfile: docker/api.Dockerfile
        args:
            DATABASE_URL: ${DATABASE_URL}
    depends_on:
        migrations:
            condition: service_completed_successfully

services:
    mariadb:
        container_name: vanilla-mariadb
        image: mariadb:11.4
        volumes:
            - vanilla-mariadb-data:/var/lib/mysql
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        healthcheck:
            test: sh -c "healthcheck.sh --connect --innodb_initialized"
            interval: 3s
            retries: 30

    migrations:
        container_name: vanilla-migrations
        build:
            context: .
            dockerfile: docker/migrations.Dockerfile
            args:
                DATABASE_URL: ${DATABASE_URL}
        command: prisma migrate deploy
        depends_on:
            mariadb:
                condition: service_healthy

    api:
        <<: *api
        container_name: vanilla-api
        command: npm run start:api
        ports:
            - "7000:7000"

    join:
        <<: *api
        container_name: vanilla-join
        command: node dist/join/Join.js
        ports:
            - "6113:6113"

    blizzard:
        <<: *vanilla
        container_name: vanilla-blizzard
        command: npm run start -- -n Blizzard -p 6114
        ports:
            - "6114:6114"

volumes:
    vanilla-mariadb-data:
